version: "3.4"
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.15.1
    ports:
     - "9201:9200"
    expose:
      - "9200"
    environment:
      SERVER_NAME: "elasticsearch"
      ES_JAVA_OPTS: "-Xms512m -Xmx512m"
      network.bind_host: 0.0.0.0
      network.host: 0.0.0.0
      discovery.type: single-node
    volumes:
      - es-data:/usr/share/elasticsearch/data
    networks:
      - elastic
volumes:
  es-data:
    driver: local
networks:
  elastic:
    driver: bridge
